### ISSUE TITLE
Hoppers stop working or do not work properly

### ISSUE THREAD

**Issue by Nat392** [ColinHDev/VanillaHopper#7]
Hello,

I've come to see you following several reports from our players who are reporting bugs on your latest version of your plugin (we're on the latest version of PocketMine 5).

We're getting reports that on server restarts, or just when the world unloads, the hoppers stop working or slow down (for example, we're getting reports that it transfers 1 item out of 2, etc.).

Here's our configuration:

```yml
# Define the number of ticks a hopper is on cooldown after pushing, pulling or picking up an item.
# Default: 8
hopper.transferCooldown: 8
# Define the number of items the hopper tries to push, pull or pick up when updated.
# Default: 1
hopper.itemsPerUpdate: 8
# Define how many hoppers are allowed to be updated every tick.
# Default: 0 (disabled)
hopper.updatesPerTick: 0
```

We suspect there may be a problem with the tiles, which have recently been modified.

Thanks in advance
